Rebalance Chosen and Their envinronment
long-war-2/lwotc pull request #1159
Opened 2020-11-20 11:27 UTC by Grobobobo

2020-11-20 16:05 UTC, pledbrook requested changes
Please rename "Obj_ChosenAvengerDefense.umap" to "Obj_ChosenAvengerDefense_LW.umap" to differentiate it from the vanilla file. Also please add "Needs Translation" markers to the localisation content that has changed.

2020-11-20 16:05 UTC, pledbrook commented on LongWarOfTheChosen/Src/LW_PerkPack_Integrated/Classes/X2Effect_BloodThirst.uc
> +    return 0;
```suggestion

	if (AppliedData.AbilityResultContext.HitResult != eHit_Miss &&
		AbilityState.SourceWeapon == EffectState.ApplyEffectParameters.ItemStateObjectRef)
	{
		TargetUnit = XComGameState_Unit(TargetDamageable);
		if (TargetUnit != none)
		{
			if (!bflatdamage)
			{
				return int (CurrentDamage * (BloodThirstDMGPCT / 100));
			}
			else
			{
				return BloodThirstFlatDMG;
			}
		}
	}
	return 0;
```

2020-11-20 16:05 UTC, pledbrook commented on LongWarOfTheChosen/Src/LW_Toolbox_Integrated/Classes/XComGameState_Unit_LWRandomizedStats.uc
> +	if (`SYNC_RAND(100) < default.COMINT_BASE_SWAP_CHANCE && !(Unit.GetMyTemplateName() == 'RebelSoldierProxy' || Unit.GetMyTemplateName() == 'RebelSoldierProxyM2' || Unit.GetMyTemplateName() == 'RebelS
You could simply check whether the name contains (using `InStr()`) the text "RebelSoldierProxy" rather than having three separate checks.

2020-11-20 16:06 UTC, pledbrook commented
Also, I don't see a problem having these changes in a single commit, as they're almost all connected.

2020-11-20 21:28 UTC, Grobobobo commented on LongWarOfTheChosen/Config/XComGameData.ini
> +-ChosenStrengths=Shogun
No, because that's not the array we actually use to gain strengths.

2020-11-20 21:33 UTC, Grobobobo commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/Utilities_LW.uc
> +		else if (`SYNC_RAND_STATIC(100) < MagChance)
Won't happen because the older techs chance is set to 100.

2020-11-20 21:35 UTC, Grobobobo commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2LWAbilitiesModTemplate.uc
> +	}
I know, but shouldn't matter in this case because I'm looking for only one specific instance, not multiple.

2020-11-20 22:13 UTC, Grobobobo commented on LongWarOfTheChosen/Config/XComGameData_WeaponData.ini
> +-ChosenShotgunUpgrades=MissDamageUpgrade_Sup
Actually, this config is potentially misleading, since the actual change is changing the dependency function that acquires them to none.

2020-11-20 22:14 UTC, Grobobobo commented on LongWarOfTheChosen/Config/XComGameData_WeaponData.ini
> +-ChosenShotgunUpgrades=MissDamageUpgrade_Sup
It's probably better to remove it at least for that reason.

2020-11-20 22:32 UTC, pledbrook commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/Utilities_LW.uc
> +		else if (`SYNC_RAND_STATIC(100) < MagChance)
Laser is not always set to 100. Anyway, I'd need to do some probability calculations to work out whether this is disadvantaging the player compared to a single roll.

2020-11-20 22:38 UTC, Grobobobo commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/Utilities_LW.uc
> +		else if (`SYNC_RAND_STATIC(100) < MagChance)
It is if you've research coilguns and mag, so there's no way to fail coil chance, mag chance AND laser chance at the same time.

2020-11-21 11:07 UTC, pledbrook approved these changes

2020-11-21 13:03 UTC, merged