Some loc fixes
long-war-2/lwotc pull request #1169
Opened 2020-11-24 08:10 UTC by FlashVanMaster

2020-11-24 08:39 UTC, FlashVanMaster commented
New and old abilities

2020-12-02 09:18 UTC, pledbrook requested changes
Thank you! This was a lot of work and much appreciated. I've just fixed up some markers via GitHub suggestions. You should be able to click on the "Add suggestion to batch" button for each of them and then commit that batch once they're all added.

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/LW_FactionBalance/LW_FactionBalance.rus
> +; LWOTC Needs Translation
```suggestion
; LWOTC Translated
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/LW_FactionBalance/LW_FactionBalance.rus
> +; End Translation
```suggestion
; End Translated
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/LW_Overhaul.rus
> +;LWOTC needs translated
```suggestion
;LWOTC translated
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/LW_WeaponsAndArmor/XComGame.rus
> +; LWOTC Needs Translation
```suggestion
; LWOTC Translated
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/XComGame.int
>  ; LWOTC Needs Translation
```suggestion
; LWOTC Translated
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/XComGame.int
>  ; End Translation
```suggestion
; End Translated
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/XComGame.rus
> +
```suggestion
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/XComGame.rus
> +;End Trasnlated_2
```suggestion
;End Translated
```

2020-12-02 09:18 UTC, pledbrook commented on LongWarOfTheChosen/Localization/XComGame.rus
> +; End Translated
Some of these [will change shortly](https://github.com/long-war-2/lwotc/pull/1178/files#diff-0c3559cce935fc36aef53dcc259c82aeacc54c87769f5883b5fe3cd0d51b32d2L5235).

2020-12-03 11:23 UTC, pledbrook approved these changes
This is great, thanks. I will postpone merging this until the Reaper changes have been merged.

2020-12-03 19:37 UTC, merged