More Psi abilities for Faceless chance reduction
long-war-2/lwotc pull request #1261
Opened 2021-03-03 18:04 UTC by K1ruka

The edited line now checks for one of the following abilities: Mind Merge, Soulfire, or Insanity for Faceless chance reduction, rather than just Mind Merge. This is for better compatibility with alternate Psi setups such as Psionics Overhaul V3 with Mod Jam.

2021-03-28 20:57 UTC, Grobobobo commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/XComGameState_LWOutpost.uc
> +			if (Unit.HasSoldierAbility('MindMerge') || Unit.HasSoldierAbility('Soulfire') || Unit.HasSoldierAbility('Insanity'))
If you're doing this, wouldn't be best to make it configurable at this point? I think there can be a batter implementation there.

2021-03-29 10:01 UTC, Grobobobo requested changes

2021-03-29 10:01 UTC, Grobobobo commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/XComGameState_LWOutpost.uc
> +			foreach default.FacelessReductionPsiAbilities(PsionAbilityName)
This time the multiplier will trigger for EACH of those abilities. Use find instead of the loop.

2021-03-29 10:32 UTC, Grobobobo requested changes
Pretty sure this still doesn't work.

2021-03-29 10:32 UTC, Grobobobo commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/XComGameState_LWOutpost.uc
> +	local name PsionAbilityName;
Where is that set? What's the Connection between PsionAbilityName and FacelessReductionPsiAbilities?

2021-04-26 15:44 UTC, pledbrook reviewed
I'm not a huge fan of the arbitrary cap on the number of abilities that can have an effect. I think I'll have a go at implementing a different algorithm that makes additional abilities contribute to the reduction, but not by much. So two abilities should be noticeably better than 1, but beyond that, it's not really worth adding more.

2021-04-29 16:41 UTC, pledbrook commented
Added in [this commit](https://github.com/long-war-2/lwotc/commit/54ff13e4bbe999fb6ef5dd4acae0ae5a12116cf5).

2021-04-29 16:41 UTC, closed without merging