Clear job prohibitions after liberation
long-war-2/lwotc pull request #1413
Opened 2021-08-16 12:44 UTC by GafrieGithub

This clears job prohibitions and retributions affecting the region when the region is liberated. The ingame notification may occur slightly after, but you can start assigning rebels to the job immediately.
Was reported in #686.

2021-08-25 08:58 UTC, pledbrook requested changes
Thanks for the fix. One change needed, but also a question: have you tested this? Just want to make sure. I think it should work, but that's not a reliable gauge. I'm just a little unsure that the outpost game state is reliably updated shortly after the alien activity is completed.

2021-08-25 08:58 UTC, pledbrook commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultAlienActivities.uc
> +		NewGameState.AddStateObject(Outpost);
This should use the new WOTC API for game state objects:

```suggestion
		Outpost = XComGameState_LWOutpost(NewGameState.ModifyStateObject(class'XComGameState_LWOutpost', Outpost.ObjectID));
```

2021-08-25 08:58 UTC, pledbrook commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultAlienActivities.uc
> +			OutPost.ProhibitedJobs[k].DaysLeft = 0;
```suggestion
			Outpost.ProhibitedJobs[k].DaysLeft = 0;
```

2021-08-25 08:58 UTC, pledbrook commented on LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2StrategyElement_DefaultAlienActivities.uc
> +			OutPost.CurrentRetributions[k].DaysLeft = 0;
```suggestion
			Outpost.CurrentRetributions[k].DaysLeft = 0;
```

2021-08-25 10:25 UTC, GafrieGithub commented
> 
> 
> Thanks for the fix. One change needed, but also a question: have you tested this? Just want to make sure. I think it should work, but that's not a reliable gauge. I'm just a little unsure that the outpost game state is reliably updated shortly after the alien activity is completed.

I did test this as such: after liberation I could immediately assign rebels on the previously forbidden job. The notification of prohibition clearing appeared few hours later.

Regarding changing CreateStateObject to ModifyStateObject, I admit that I don't know full workings of this system, but I want to point out that the code elsewhere nearly always uses CreateStateObject when outpost is updated in similar manner. I don't know if it matters or not.

2021-08-25 10:28 UTC, pledbrook commented
> but I want to point out that the code elsewhere nearly always uses CreateStateObject when outpost is updated in similar manner

A fair point. This is because that code is LW2, which only had access to the original XCOM 2 API. Any new code we add should use `CreateNewStateObject()` and `ModifyStateObject()`. It's mostly for clarity and to remove the need for the extra `AddStateObject()` call.

2021-09-09 09:28 UTC, pledbrook approved these changes

2021-09-09 09:31 UTC, merged

2021-09-09 09:31 UTC, pledbrook commented
Thanks.